{{- if or (eq .Values.installMode "all") (eq .Values.installMode "controller-only") }}
apiVersion: v1
kind: Secret
metadata:
  name: workload-variant-autoscaler-controller-manager-token-manual
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: workload-variant-autoscaler-controller-manager
type: kubernetes.io/service-account-token{{- end }}
