{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "workload-variant-autoscaler.fullname" . }}-hpa
  namespace: {{ .Values.llmd.namespace }}
  labels:
    {{- include "workload-variant-autoscaler.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-decode" .Values.llmd.modelName }}
  # minReplicas: 0  # scale to zero - alpha feature
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleUp.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.hpa.behavior.scaleUp.selectPolicy }}
      policies:
      {{- range .Values.hpa.behavior.scaleUp.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.hpa.behavior.scaleDown.selectPolicy }}
      policies:
      {{- range .Values.hpa.behavior.scaleDown.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
  metrics:
  - type: External
    external:
      metric:
        name: inferno_desired_replicas
        selector:
          matchLabels:
            variant_name: {{ printf "%s-decode" .Values.llmd.modelName }}
            exported_namespace: {{ .Values.llmd.namespace }}
            {{- if .Values.wva.controllerInstance }}
            controller_instance: {{ .Values.wva.controllerInstance | quote }}
            {{- end }}
      target:
        type: AverageValue
        averageValue: {{ .Values.hpa.targetAverageValue | quote }}
{{- end }}
